In [22]:
import pandas as pd

In [23]:
# json path
spaceflight_data = pd.read_csv(f'../../../data/raw/global_involvement/space_missions/space_corrected.csv')

spaceflight_data

,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50,Success
1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65,Success
4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145,Success
...,...,...,...,...,...,...,...
4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure
4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA","Sat Feb 01, 1958 03:48 UTC",Juno I | Explorer 1,StatusRetired,NaN,Success
4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,StatusRetired,NaN,Failure
4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success
4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success

In [24]:
spaceflight_data.columns

Index(['Company Name', 'Location', 'Datum', 'Detail', 'Status Rocket',
       ' Rocket', 'Status Mission'],
      dtype='object')

In [25]:
cols_to_rename = {
    'Company Name': 'company_name',
    'Location': 'location',
    'Datum': 'date',
    'Detail': 'detail',
    'Status Rocket': 'status_rocket',
    'Rocket': 'rocket',
    'Status Mission': 'status_mission',
     
}

spaceflight_data.rename(columns=cols_to_rename, inplace=True)

spaceflight_data

,company_name,location,date,detail,status_rocket,Rocket,status_mission
0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50,Success
1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65,Success
4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145,Success
...,...,...,...,...,...,...,...
4319,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure
4320,AMBA,"LC-26A, Cape Canaveral AFS, Florida, USA","Sat Feb 01, 1958 03:48 UTC",Juno I | Explorer 1,StatusRetired,NaN,Success
4321,US Navy,"LC-18A, Cape Canaveral AFS, Florida, USA","Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,StatusRetired,NaN,Failure
4322,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success
4323,RVSN USSR,"Site 1/5, Baikonur Cosmodrome, Kazakhstan","Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success

In [26]:
# splitting the column
spaceflight_data[['address', 'country']] = spaceflight_data['location'].str.rsplit(',', n=1, expand=True)

spaceflight_data.drop(['location'], axis=1, inplace=True)

# stripping any leading/trailing whitespace
spaceflight_data['address'] = spaceflight_data['address'].str.strip()
spaceflight_data['country'] = spaceflight_data['country'].str.strip()

spaceflight_data

,company_name,date,detail,status_rocket,Rocket,status_mission,address,country
0,SpaceX,"Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50,Success,"LC-39A, Kennedy Space Center, Florida",USA
1,CASC,"Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",China
2,SpaceX,"Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,"Pad A, Boca Chica, Texas",USA
3,Roscosmos,"Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65,Success,"Site 200/39, Baikonur Cosmodrome",Kazakhstan
4,ULA,"Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145,Success,"SLC-41, Cape Canaveral AFS, Florida",USA
...,...,...,...,...,...,...,...,...
4319,US Navy,"Wed Feb 05, 1958 07:33 UTC",Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,"LC-18A, Cape Canaveral AFS, Florida",USA
4320,AMBA,"Sat Feb 01, 1958 03:48 UTC",Juno I | Explorer 1,StatusRetired,NaN,Success,"LC-26A, Cape Canaveral AFS, Florida",USA
4321,US Navy,"Fri Dec 06, 1957 16:44 UTC",Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,"LC-18A, Cape Canaveral AFS, Florida",USA
4322,RVSN USSR,"Sun Nov 03, 1957 02:30 UTC",Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,"Site 1/5, Baikonur Cosmodrome",Kazakhstan
4323,RVSN USSR,"Fri Oct 04, 1957 19:28 UTC",Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,"Site 1/5, Baikonur Cosmodrome",Kazakhstan

In [27]:
# find rows where 'date' does not end with 'UTC'
mask = ~spaceflight_data['date'].str.endswith('UTC')


# Append ' 0:00 UTC' to these rows
spaceflight_data.loc[mask, 'date'] = spaceflight_data.loc[mask, 'date'] + ' 0:00 UTC'

In [28]:
spaceflight_data['date'] = pd.to_datetime(spaceflight_data['date'], format='%a %b %d, %Y %H:%M %Z')

spaceflight_data.dtypes

company_name                   object
date              datetime64[ns, UTC]
detail                         object
status_rocket                  object
 Rocket                        object
status_mission                 object
address                        object
country                        object
dtype: object

In [29]:
spaceflight_data

,company_name,date,detail,status_rocket,Rocket,status_mission,address,country
0,SpaceX,2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50,Success,"LC-39A, Kennedy Space Center, Florida",USA
1,CASC,2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",China
2,SpaceX,2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success,"Pad A, Boca Chica, Texas",USA
3,Roscosmos,2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65,Success,"Site 200/39, Baikonur Cosmodrome",Kazakhstan
4,ULA,2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145,Success,"SLC-41, Cape Canaveral AFS, Florida",USA
...,...,...,...,...,...,...,...,...
4319,US Navy,1958-02-05 07:33:00+00:00,Vanguard | Vanguard TV3BU,StatusRetired,NaN,Failure,"LC-18A, Cape Canaveral AFS, Florida",USA
4320,AMBA,1958-02-01 03:48:00+00:00,Juno I | Explorer 1,StatusRetired,NaN,Success,"LC-26A, Cape Canaveral AFS, Florida",USA
4321,US Navy,1957-12-06 16:44:00+00:00,Vanguard | Vanguard TV3,StatusRetired,NaN,Failure,"LC-18A, Cape Canaveral AFS, Florida",USA
4322,RVSN USSR,1957-11-03 02:30:00+00:00,Sputnik 8K71PS | Sputnik-2,StatusRetired,NaN,Success,"Site 1/5, Baikonur Cosmodrome",Kazakhstan
4323,RVSN USSR,1957-10-04 19:28:00+00:00,Sputnik 8K71PS | Sputnik-1,StatusRetired,NaN,Success,"Site 1/5, Baikonur Cosmodrome",Kazakhstan

In [31]:
spaceflight_data.to_csv(f'../../../data/processed/global_involvement/space_missions/next_spaceflight_processed.csv', index=False)